//SELECT DROPDOWNS

export const rbiLisenceTypes = [
  {
    type: "Investment and Credit Company (ICC)",
    value: "Investment and Credit Company",
  },
  {
    type: "Infrastructure Finance Company (IFC)",
    value: "Infrastructure Finance Company",
  },
  {
    type: "Infrastructure Debt Fund (IDF)",
    value: "Infrastructure Debt Fund",
  },
  {
    type: "Micro Finance Institution (MFI)",
    value: "Micro Finance Institution",
  },
  {
    type: "Core Investment Company (CIC)",
    value: "Core Investment Company",
  },
  {
    type: "Asset Finance Company (AFC)",
    value: "Asset Finance Company",
  },
  {
    type: "Housing Finance Company (HFC)",
    value: "Housing Finance Company",
  },
  {
    type: "Peer to Peer Lending Platform (P2P)",
    value: "Peer to Peer Lending Platform",
  },
  {
    type: "Account Aggregator (AA)",
    value: "Account Aggregator",
  },
  {
    type: "Factor (Factor)",
    value: "Factor",
  },
  {
    type: "Mortgage Guarantee Company (MGC)",
    value: "Mortgage Guarantee Company",
  },
  {
    type: "Non-Operative Financial Holding Company (NOFHC)",
    value: "Non-Operative Financial Holding Company",
  },
];

export const lpconfigLoanTypes = [
  { label: "Gold Loan", value: "Gold Loan" },
  { label: "Personal Loan", value: "Personal Loan" },
  { label: "Business Loan", value: "Business Loan" },
  { label: "Two-Wheeler Loan", value: "Two-Wheeler Loan" },
  { label: "Used Car Loan", value: "Used Car Loan" },
  { label: "New Car Loan", value: "New Car Loan" },
  { label: "Loan Against Property (LAP)", value: "Loan Against Property" },
  { label: "Home Loan", value: "Home Loan" },
  { label: "Education Loan", value: "Education Loan" },
  { label: "Consumer Durable Loan", value: "Consumer Durable Loan" },
  { label: "Agricultural Loan", value: "Agricultural Loan" },
  { label: "SME/MSME Loan", value: "SME/MSME Loan" },
  { label: "Microfinance Loan", value: "Microfinance Loan" },
  {
    label: "Construction Equipment Loan",
    value: "Construction Equipment Loan",
  },
  { label: "Commercial Vehicle Loan", value: "Commercial Vehicle Loan" },
  { label: "Working Capital Loan", value: "Working Capital Loan" },
  { label: "Invoice Financing", value: "Invoice Financing" },
  { label: "Loan Against Securities", value: "Loan Against Securities" },
  { label: "Top-Up Loan", value: "Top-Up Loan" },
  { label: "Balance Transfer Loan", value: "Balance Transfer Loan" },
];

export const lpconfigLoanPurposes = [
  { label: "Education", value: "Education" },
  { label: "Home Renovation", value: "Home Renovation" },
  { label: "Business Expansion", value: "Business Expansion" },
  { label: "Working Capital", value: "Working Capital" },
  { label: "Debt Consolidation", value: "Debt Consolidation" },
  { label: "Medical Expenses", value: "Medical Expenses" },
  { label: "Wedding", value: "Wedding" },
  { label: "Travel", value: "Travel" },
  { label: "Vehicle Purchase", value: "Vehicle Purchase" },
  { label: "Purchase of Machinery", value: "Purchase of Machinery" },
  { label: "Construction of House", value: "Construction of House" },
  { label: "Purchase of Land", value: "Purchase of Land" },
  {
    label: "Purchase of Commercial Property",
    value: "Purchase of Commercial Property",
  },
  { label: "Agricultural Activities", value: "Agricultural Activities" },
  { label: "Emergency Fund", value: "Emergency Fund" },
  { label: "Loan Against Deposit", value: "Loan Against Deposit" },
  { label: "House Purchase", value: "House Purchase" },
  { label: "Equipment Financing", value: "Equipment Financing" },
  { label: "Export/Import Financing", value: "Export/Import Financing" },
  { label: "Student Loan (Overseas)", value: "Student Loan (Overseas)" },
];

export const lpConfigRepaymentScheduleTypes = [
  { label: "EMI", value: "EMI" },
  { label: "Bullet", value: "Bullet" },
  { label: "Lump Sum", value: "Lump Sum" },
  { label: "Step-Up", value: "Step-Up" },
  { label: "Step-Down", value: "Step-Down" },
  { label: "Interest Only", value: "Interest Only" },
  { label: "Custom", value: "Custom" },
];

export const lpConfigEmiFrequencies = [
  { label: "Monthly", value: "Monthly" },
  { label: "Bi-Monthly", value: "Bi-Monthly" },
  { label: "Quarterly", value: "Quarterly" },
  { label: "Half-Yearly", value: "Half-Yearly" },
  { label: "Annually", value: "Annually" },
  { label: "Weekly", value: "Weekly" },
  { label: "Daily", value: "Daily" },
];

export const lpConfigGoldPurityOptions = [
  { label: "75% 18K", value: "75% 18K" },
  { label: "80% 19K", value: "80% 19K" },
  { label: "85% 20K", value: "85% 20K" },
  { label: "91.6% 22K", value: "91.6% 22K" },
  { label: "95.8% 23K", value: "95.8% 23K" },
  { label: "99.9% 24K", value: "99.9% 24K" },
];

export const lpConfigCollateralTypes = [
  { label: "Gold", value: "Gold" },
  { label: "Property", value: "Property" },
  { label: "Vehicle", value: "Vehicle" },
  { label: "Securities", value: "Securities" },
  { label: "Cash", value: "Cash" },
  { label: "Inventory", value: "Inventory" },
  { label: "Other", value: "Other" },
];

//NBFC SKELETON
export const formSkeletons = [
  {
    id: "nbfcEstablishmentDetails",
    title: "1. NBFC Establishment Details",
  },
  {
    id: "nbfcContactDetails",
    title: "2. NBFC Contact Details",
  },
  {
    id: "requiredDocs",
    title: "3. Upload Required Documents",
  },
];



// DISBURSEMENT

export const DisbursementFileTags = [
    {name: "Customer_Name", value: "customerName"},
    {name: "Borrower_Name", value: "borrowerName"},
    {name: "Loan_ID", value: "loanId"},
    {name: "Loan_Account_Number", value: "loanAccountNumber"},
    {name: "Loan_Ammount", value: "loanAmount"},
    {name: "Loan_Term", value: "loanTerm"},
    {name: "Sanctioned_Amount", value: "sanctionedAmount"},
    {name: "Disbursed_Amount", value: "disbursedAmount"},
    {name: "Disbursement_Date", value: "disbursementDate"},
    {name: "Tenure", value: "tenure"},
    {name: "Interest_Rate", value: "interestRate"},
    {name: "ROI", value: "roi"},
];

export const DisbursementFileInferTableHeaders = [
  { name: "Platform Field", key: "pf" },
  { name: "Expected Column Name (from NBFC file)", key: "ec" },
  { name: "Required", key: "r" },
];

//BRE

export const breConfigTabs = [
  { name: "1. Bureau", value: "bureau" },
  { name: "2. Bank Statement", value: "bankStatement" },
  { name: "3. KYC", value: "kyc" },
  { name: "4. Income", value: "income" },
  { name: "5. Occupation", value: "occupation" },
  { name: "6. Demographic", value: "demographic" },
];

export const breConfigTableHeaders = [
  {
    name: "Parameter",
    key: "parameter",
    icon: "/images/icons/bre_config_th_icon.svg",
  },
  {
    name: "Value",
    key: "value",
    icon: "/images/icons/bre_config_th_icon.svg",
  },
  {
    name: "Weightage",
    key: "weightage",
    icon: "/images/icons/bre_config_th_icon.svg",
  },
  {
    name: "Mandatory",
    key: "mandatory",
  },
];

//bre params
export const breConfigBureauParams = [
  {
    name: "Credit Score",
    key: "creditScore",
    subtitle: "Minimum credit score required",
  },
  {
    name: "Bureau Vintage",
    key: "bureauVintage",
    subtitle: "History in months",
  },
  {
    name: "DPD (Days Past Due)",
    key: "dpd",
    subtitle: "Maximum DPD allowed",
  },
  {
    name: "Number of Enquiries",
    key: "numOfEnquiries",
    subtitle: "Max enquiries in last 3/6 months",
  },
  {
    name: "Active Loans Numbers",
    key: "activeLoans",
    subtitle: "Numbers of secured/unsecured loans",
  },
  {
    name: "Write-off/settlement ac",
    key: "writeOffSettlement",
    subtitle: "Past write-offs or settlements",
  },
];

export const breConfigBankStatementParams = [
  {
    name: "Average Monthly Balance",
    key: "avgMonthlyBalance",
    subtitle: "Minimum Average Monthly Balance required",
    type: "money",
  },
  {
    name: "Monthly Credits",
    key: "monthlyCredits",
    subtitle: "Minimum salary/income inflow",
    type: "money",
  },
  {
    name: "FOIR",
    key: "foir",
    subtitle: "Max EMI to Income Ratio",
    type: "percent",
  },
  {
    name: "Debit Bounce Count",
    key: "debitBounceCount",
    subtitle: "Max Bounce in last 3/6 months",
  },
  {
    name: "Overdraft Instances",
    key: "overdraftInstances",
    subtitle: "Max OD instances in last 3/6 months",
  },
  {
    name: "EOD Balance Threshold",
    key: "eodBalanceThreshold",
    subtitle: "Min EOD Balance",
    type: "money",
  },
];

export const breConfigKycParams = [
  {
    name: "PAN Verification",
    key: "panVerification",
    subtitle: "Minimum Name match %",
    type: "percent",
  },
  {
    name: "Aadhaar Authentication",
    key: "aadharAuth",
    subtitle: "Minimum Name match %",
    type: "percent",
  },
  {
    name: "Video KYC",
    key: "videoKyc",
    subtitle: "Minimum face match %",
    type: "percent",
  },
  { name: "Min Age", key: "minAge", subtitle: "Min Age of applicant in years" },
  { name: "Max Age", key: "maxAge", subtitle: "Max Age of applicant in years" },
];

export const breConfigIncomeParams = [
  {
    name: "ITR Filing",
    key: "itrFiling",
    subtitle: "Minimum Name match %",
    type: "percent",
  },
  {
    name: "GST Filing",
    key: "gstFiling",
    subtitle: "Minimum GST filing value",
    type: "money",
  },
  {
    name: "Udyam Verification",
    key: "udyamVerification",
    subtitle: "Min udyam details match %",
    type: "percent",
  },
  {
    name: "Source of Income",
    key: "sourceOfIncome",
    subtitle: "Salaried / Self-employed/ Business",
  },
  {
    name: "Consistency",
    key: "consistency",
    subtitle: "Min consistency of income in months",
  },
];

export const breConfigOccupationParams = [
  {
    name: "Employer Type",
    key: "employerType",
    subtitle: "Govt / Pvt / Self-employed",
  },
  {
    name: "Employment Stability",
    key: "employmentStability",
    subtitle: "Minimum experience in months ",
  },
  {
    name: "Business Vintage",
    key: "businessVintage",
    subtitle: "Min vintage in months",
  },
];

export const breConfigDemographicParams = [
  {
    name: "Pin Code Risk Mapping",
    key: "pinCodeRiskMapping",
    subtitle: "Flag based on high-risk geographic areas.",
  },
];

//bre - tab content (ALL TABS)
export const breConfigTabContent = [
  {
    value: "bureau",
    title: "Bureau Rules",
    subtitle: "Get creditworthiness and repayment history",
    navTo: "bankStatement",
    paramsArr: breConfigBureauParams,
  },
  {
    value: "bankStatement",
    title: "Bank Statement",
    subtitle: "Get cash flow assessment & repayment ability",
    navTo: "kyc",
    paramsArr: breConfigBankStatementParams,
  },
  {
    value: "kyc",
    title: "KYC",
    subtitle: "Get Identity validation and fraud prevention",
    navTo: "income",
    paramsArr: breConfigKycParams,
  },
  {
    value: "income",
    title: "Income",
    subtitle: "Get Validate income consistency",
    navTo: "occupation",
    paramsArr: breConfigIncomeParams,
  },
  {
    value: "occupation",
    title: "Occupation",
    subtitle: "Understand stability and risk based on employment",
    navTo: "demographic",
    paramsArr: breConfigOccupationParams,
  },
  {
    value: "demographic",
    title: "Demographic",
    subtitle: "Understand stability and risk based on employment",
    navTo: "",
    paramsArr: breConfigDemographicParams,
  },
];

//LOAN PRODUCT CONFIG

export const loanProductConfigTabs = [
  { name: "1. Product Info", key: "productInfo" },
  { name: "2. Loan Amount & Tenure", key: "loanAmountAndTenure" },
  { name: "3. Charges & Fees", key: "chargesAndFees" },
  { name: "4. Repayment & Schedule", key: "repaymentAndSchedule" },
  { name: "5. Collateral & Risk Controls", key: "collateralAndRiskControls" }
];

export const loanProductConfigTableHeaders = [
  {
    name: "Parameter",
    key: "parameter",
    icon: "/images/icons/bre_config_th_icon.svg",
  },
  {
    name: "Value",
    key: "value",
    icon: "/images/icons/bre_config_th_icon.svg",
  },
  {
    name: "Mandatory",
    key: "mandatory",
  },
];

export const loanProductConfigProductInfoParams = [
  {
    name: "Loan Type",
    key: "loanType",
    subtitle: "Select the type of loan being configured",
    dropdown: lpconfigLoanTypes,
  },
  {
    name: "Loan Category / Purpose",
    key: "loanCategory",
    subtitle: "Specify the purpose for which the loan is offered",
    dropdown: lpconfigLoanPurposes,
  },
];

export const loanProductConfigLoanAmountParams = [
  {
    name: "Max Disbursement Cap",
    key: "maxDisbursementCap",
    subtitle: "Disbursement limit for this loan product",
    type: "money",
  },
  {
    name: "Min Loan Amount",
    key: "minLoanAmount",
    subtitle: "Lowest amount that can be disbursed",
    type: "money",
  },
  {
    name: "Max Loan Amount",
    key: "maxLoanAmount",
    subtitle: "Loan exposure allowed per customer across products",
    type: "money",
  },
  {
    name: "Min Tenure",
    key: "minTenure",
    subtitle: "Shortest allowable repayment period in Months",
  },
  {
    name: "Max Tenure",
    key: "maxTenure",
    subtitle: "Longest allowable repayment period",
  },
];

export const loanProductConfigChargesParams = [
  {
    name: "Rate of Interest (ROI)",
    key: "roi",
    subtitle: "Annual interest rate applicable",
    type: "percent",
  },
  {
    name: "Processing Fee",
    key: "processingFee",
    subtitle: "Fixed one-time loan setup fee",
    type: "money",
  },
  {
    name: "Service Fee",
    key: "serviceFee",
    subtitle: "Additional service charge on the loan",
    type: "money",
  },
  {
    name: "GST on Service Fee ",
    key: "gstOnServiceFee",
    subtitle: "GST percentage applicable on the service fee",
    type: "percent",
  },
];

export const loanProductConfigRepaymentParams = [
  {
    name: "Repayment Schedule Type",
    key: "repaymentScheduleType",
    subtitle: "Repayment structure (e.g., EMI, Bullet)",
    dropdown: lpConfigRepaymentScheduleTypes,
  },
  {
    name: "EMI Frequency / Cycle",
    key: "emiFrequency",
    subtitle: "Select how often repayments will be made",
    dropdown: lpConfigEmiFrequencies,
  },
  {
    name: "Moratorium Period",
    key: "moratoriumPeriod",
    subtitle: "Grace period before repayment starts (if applicable)",
  }
];

export const loanProductConfigCollateralParams = [
  {
    name: "Gold Purity %",
    key: "goldPurity",
    subtitle: "Set minimum acceptable purity for pledged gold",
    dropdown: lpConfigGoldPurityOptions,
  },
  {
    name: "Loan-to-Value (LTV) %",
    key: "ltvPercentage",
    subtitle: "Minimum experience in months ",
    type: "percent",
  },
  {
    name: "Collateral Type Required?",
    key: "collateralTypeRequired",
    subtitle: "Indicate if the loan requires any form of security",
    dropdown: lpConfigCollateralTypes,
  },
];

//loan product - tab content (ALL TABS)
export const loanProductConfigTabContent = [
  {
    value: "productInfo",
    title: "Product Info",
    subtitle: "Get creditworthiness and repayment history",
    navTo: "loanAmountAndTenure",
    paramsArr: loanProductConfigProductInfoParams,
  },
  {
    value: "loanAmountAndTenure",
    title: "Loan Amount & Tenure",
    subtitle: "Get cash flow assessment & repayment ability.",
    navTo: "chargesAndFees",
    paramsArr: loanProductConfigLoanAmountParams,
  },
  {
    value: "chargesAndFees",
    title: "Charges & Fees",
    subtitle: "Get Identity validation and fraud prevention.",
    navTo: "repaymentAndSchedule",
    paramsArr: loanProductConfigChargesParams,
  },
  {
    value: "repaymentAndSchedule",
    title: "Repayment & Schedule",
    subtitle: "Get Validate income consistency.",
    navTo: "collateralAndRiskControls",
    paramsArr: loanProductConfigRepaymentParams,
  },
  {
    value: "collateralAndRiskControls",
    title: "Collateral & Risk Controls",
    subtitle: "Understand stability and risk based on employment",
    navTo: "/",
    paramsArr: loanProductConfigCollateralParams,
  },
];



//DATA TABLE

export const tableData: tableDataParams[] = [
  {
    sl: 1,
    nbfcId: "MFL362950628",
    appId: "APP1958682846",
    status: "Approved",
    name: "Titanium",
    tenure: 36,
    nbfcDisbursedAmount: 486123,
    posAmount: 63736,
  },
  {
    sl: 2,
    nbfcId: "MFL134126396",
    appId: "APP1127978094",
    status: "Approved",
    name: "Beta Credit",
    tenure: 48,
    nbfcDisbursedAmount: 214629,
    posAmount: 70990,
  },
  {
    sl: 3,
    nbfcId: "MFL868820204",
    appId: "APP7635473142",
    status: "Approved",
    name: "Beta Credit",
    tenure: 30,
    nbfcDisbursedAmount: 215574,
    posAmount: 127757,
  },
  {
    sl: 4,
    nbfcId: "MFL849621470",
    appId: "APP7110082321",
    status: "Rejected",
    name: "Titanium",
    tenure: 24,
    nbfcDisbursedAmount: 245684,
    posAmount: 50758,
  },
  {
    sl: 5,
    nbfcId: "MFL199585092",
    appId: "APP2631775357",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 18,
    nbfcDisbursedAmount: 288208,
    posAmount: 190331,
  },
  {
    sl: 6,
    nbfcId: "MFL675770529",
    appId: "APP9256195745",
    status: "Rejected",
    name: "Titanium",
    tenure: 54,
    nbfcDisbursedAmount: 141313,
    posAmount: 86854,
  },
  {
    sl: 7,
    nbfcId: "MFL856528252",
    appId: "APP1298737106",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 30,
    nbfcDisbursedAmount: 446692,
    posAmount: 129484,
  },
  {
    sl: 8,
    nbfcId: "MFL208449460",
    appId: "APP6927597015",
    status: "Rejected",
    name: "Titanium",
    tenure: 30,
    nbfcDisbursedAmount: 337717,
    posAmount: 201277,
  },
  {
    sl: 9,
    nbfcId: "MFL324956459",
    appId: "APP8173347748",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 42,
    nbfcDisbursedAmount: 467955,
    posAmount: 368375,
  },
  {
    sl: 10,
    nbfcId: "MFL283758720",
    appId: "APP2051454923",
    status: "Approved",
    name: "Beta Credit",
    tenure: 72,
    nbfcDisbursedAmount: 342357,
    posAmount: 208943,
  },
  {
    sl: 11,
    nbfcId: "MFL835098955",
    appId: "APP1240251661",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 30,
    nbfcDisbursedAmount: 116829,
    posAmount: 115518,
  },
  {
    sl: 12,
    nbfcId: "MFL171069472",
    appId: "APP2351531223",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 36,
    nbfcDisbursedAmount: 443638,
    posAmount: 271740,
  },
  {
    sl: 13,
    nbfcId: "MFL384412919",
    appId: "APP1599707677",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 24,
    nbfcDisbursedAmount: 490588,
    posAmount: 304318,
  },
  {
    sl: 14,
    nbfcId: "MFL726563708",
    appId: "APP7010379415",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 48,
    nbfcDisbursedAmount: 214987,
    posAmount: 46262,
  },
  {
    sl: 15,
    nbfcId: "MFL217734861",
    appId: "APP8217611860",
    status: "Rejected",
    name: "Titanium",
    tenure: 12,
    nbfcDisbursedAmount: 412690,
    posAmount: 43306,
  },
  {
    sl: 16,
    nbfcId: "MFL602564736",
    appId: "APP7567496105",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 66,
    nbfcDisbursedAmount: 390049,
    posAmount: 16019,
  },
  {
    sl: 17,
    nbfcId: "MFL925276600",
    appId: "APP8047877267",
    status: "Approved",
    name: "Beta Credit",
    tenure: 36,
    nbfcDisbursedAmount: 158485,
    posAmount: 86939,
  },
  {
    sl: 18,
    nbfcId: "MFL103484630",
    appId: "APP4919706735",
    status: "Rejected",
    name: "Ultrasonic United",
    tenure: 54,
    nbfcDisbursedAmount: 427837,
    posAmount: 166471,
  },
  {
    sl: 19,
    nbfcId: "MFL918739736",
    appId: "APP4944899549",
    status: "Approved",
    name: "Ultrasonic United",
    tenure: 42,
    nbfcDisbursedAmount: 414019,
    posAmount: 179951,
  },
  {
    sl: 20,
    nbfcId: "MFL489747629",
    appId: "APP2320763135",
    status: "Rejected",
    name: "Titanium",
    tenure: 18,
    nbfcDisbursedAmount: 130369,
    posAmount: 41571,
  },
  {
    sl: 21,
    nbfcId: "MFL976198296",
    appId: "APP4289233844",
    status: "Approved",
    name: "Titanium",
    tenure: 54,
    nbfcDisbursedAmount: 167314,
    posAmount: 134592,
  },
  {
    sl: 22,
    nbfcId: "MFL751325257",
    appId: "APP6633778586",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 60,
    nbfcDisbursedAmount: 452157,
    posAmount: 350723,
  },
  {
    sl: 23,
    nbfcId: "MFL584779555",
    appId: "APP1519709079",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 60,
    nbfcDisbursedAmount: 217806,
    posAmount: 26784,
  },
  {
    sl: 24,
    nbfcId: "MFL694768704",
    appId: "APP1945826486",
    status: "Rejected",
    name: "Titanium",
    tenure: 66,
    nbfcDisbursedAmount: 137220,
    posAmount: 102778,
  },
  {
    sl: 25,
    nbfcId: "MFL133729406",
    appId: "APP8987073217",
    status: "Approved",
    name: "Ultrasonic United",
    tenure: 18,
    nbfcDisbursedAmount: 137149,
    posAmount: 77391,
  },
  {
    sl: 26,
    nbfcId: "MFL621209849",
    appId: "APP3030106617",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 72,
    nbfcDisbursedAmount: 347974,
    posAmount: 223416,
  },
  {
    sl: 27,
    nbfcId: "MFL807577342",
    appId: "APP7146318035",
    status: "Approved",
    name: "Titanium",
    tenure: 18,
    nbfcDisbursedAmount: 322077,
    posAmount: 225535,
  },
  {
    sl: 28,
    nbfcId: "MFL801642483",
    appId: "APP1422701550",
    status: "Rejected",
    name: "Titanium",
    tenure: 72,
    nbfcDisbursedAmount: 311089,
    posAmount: 187892,
  },
  {
    sl: 29,
    nbfcId: "MFL304235259",
    appId: "APP7598297060",
    status: "Approved",
    name: "Ultrasonic United",
    tenure: 30,
    nbfcDisbursedAmount: 173495,
    posAmount: 120593,
  },
  {
    sl: 30,
    nbfcId: "MFL368227631",
    appId: "APP5618742930",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 54,
    nbfcDisbursedAmount: 388528,
    posAmount: 61332,
  },
  {
    sl: 31,
    nbfcId: "MFL200140141",
    appId: "APP4645120421",
    status: "Approved",
    name: "Beta Credit",
    tenure: 12,
    nbfcDisbursedAmount: 187194,
    posAmount: 116539,
  },
  {
    sl: 32,
    nbfcId: "MFL530613729",
    appId: "APP4875962612",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 30,
    nbfcDisbursedAmount: 186317,
    posAmount: 109345,
  },
  {
    sl: 33,
    nbfcId: "MFL941889393",
    appId: "APP8667072205",
    status: "Approved",
    name: "Quantum Loans",
    tenure: 36,
    nbfcDisbursedAmount: 249552,
    posAmount: 120888,
  },
  {
    sl: 34,
    nbfcId: "MFL418587604",
    appId: "APP9841118422",
    status: "Rejected",
    name: "Ultrasonic United",
    tenure: 30,
    nbfcDisbursedAmount: 485738,
    posAmount: 294266,
  },
  {
    sl: 35,
    nbfcId: "MFL153839920",
    appId: "APP7803990970",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 12,
    nbfcDisbursedAmount: 363638,
    posAmount: 288463,
  },
  {
    sl: 36,
    nbfcId: "MFL186019028",
    appId: "APP4656488400",
    status: "Approved",
    name: "Titanium",
    tenure: 60,
    nbfcDisbursedAmount: 135924,
    posAmount: 87992,
  },
  {
    sl: 37,
    nbfcId: "MFL228727266",
    appId: "APP3446737272",
    status: "Approved",
    name: "Ultrasonic United",
    tenure: 48,
    nbfcDisbursedAmount: 403520,
    posAmount: 321699,
  },
  {
    sl: 38,
    nbfcId: "MFL550139320",
    appId: "APP2119980130",
    status: "Approved",
    name: "Beta Credit",
    tenure: 18,
    nbfcDisbursedAmount: 451129,
    posAmount: 385490,
  },
  {
    sl: 39,
    nbfcId: "MFL524971817",
    appId: "APP8067372072",
    status: "Rejected",
    name: "Ultrasonic United",
    tenure: 36,
    nbfcDisbursedAmount: 339717,
    posAmount: 175767,
  },
  {
    sl: 40,
    nbfcId: "MFL766964667",
    appId: "APP5278201677",
    status: "Approved",
    name: "Titanium",
    tenure: 54,
    nbfcDisbursedAmount: 138409,
    posAmount: 80468,
  },
  {
    sl: 41,
    nbfcId: "MFL242224154",
    appId: "APP9303285822",
    status: "Approved",
    name: "Beta Credit",
    tenure: 36,
    nbfcDisbursedAmount: 136066,
    posAmount: 125247,
  },
  {
    sl: 42,
    nbfcId: "MFL269379374",
    appId: "APP3271782991",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 36,
    nbfcDisbursedAmount: 450152,
    posAmount: 438397,
  },
  {
    sl: 43,
    nbfcId: "MFL383968123",
    appId: "APP3376077463",
    status: "Rejected",
    name: "Titanium",
    tenure: 24,
    nbfcDisbursedAmount: 242788,
    posAmount: 83860,
  },
  {
    sl: 44,
    nbfcId: "MFL838194420",
    appId: "APP7393195616",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 30,
    nbfcDisbursedAmount: 126633,
    posAmount: 22097,
  },
  {
    sl: 45,
    nbfcId: "MFL103807155",
    appId: "APP9503167458",
    status: "Rejected",
    name: "Alpha Finance",
    tenure: 12,
    nbfcDisbursedAmount: 184715,
    posAmount: 125824,
  },
  {
    sl: 46,
    nbfcId: "MFL220123666",
    appId: "APP4882343658",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 12,
    nbfcDisbursedAmount: 386046,
    posAmount: 28889,
  },
  {
    sl: 47,
    nbfcId: "MFL259014493",
    appId: "APP2845919895",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 60,
    nbfcDisbursedAmount: 121930,
    posAmount: 50404,
  },
  {
    sl: 48,
    nbfcId: "MFL325567963",
    appId: "APP3929454134",
    status: "Rejected",
    name: "Titanium",
    tenure: 42,
    nbfcDisbursedAmount: 449665,
    posAmount: 63893,
  },
  {
    sl: 49,
    nbfcId: "MFL766430218",
    appId: "APP4218981849",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 48,
    nbfcDisbursedAmount: 224118,
    posAmount: 52598,
  },
  {
    sl: 50,
    nbfcId: "MFL292587044",
    appId: "APP9292791081",
    status: "Approved",
    name: "Quantum Loans",
    tenure: 12,
    nbfcDisbursedAmount: 451224,
    posAmount: 395381,
  },
  {
    sl: 51,
    nbfcId: "MFL945436943",
    appId: "APP4011966884",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 24,
    nbfcDisbursedAmount: 300562,
    posAmount: 30302,
  },
  {
    sl: 52,
    nbfcId: "MFL976803188",
    appId: "APP9239688178",
    status: "Rejected",
    name: "Ultrasonic United",
    tenure: 30,
    nbfcDisbursedAmount: 283321,
    posAmount: 170007,
  },
  {
    sl: 53,
    nbfcId: "MFL808705238",
    appId: "APP6124453431",
    status: "Approved",
    name: "Ultrasonic United",
    tenure: 12,
    nbfcDisbursedAmount: 272103,
    posAmount: 83034,
  },
  {
    sl: 54,
    nbfcId: "MFL788785773",
    appId: "APP7482848011",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 42,
    nbfcDisbursedAmount: 456263,
    posAmount: 452321,
  },
  {
    sl: 55,
    nbfcId: "MFL380477683",
    appId: "APP2140169349",
    status: "Rejected",
    name: "Titanium",
    tenure: 18,
    nbfcDisbursedAmount: 156834,
    posAmount: 123918,
  },
  {
    sl: 56,
    nbfcId: "MFL750911797",
    appId: "APP5791662169",
    status: "Rejected",
    name: "Alpha Finance",
    tenure: 48,
    nbfcDisbursedAmount: 402298,
    posAmount: 109656,
  },
  {
    sl: 57,
    nbfcId: "MFL101815992",
    appId: "APP6141226746",
    status: "Rejected",
    name: "Titanium",
    tenure: 48,
    nbfcDisbursedAmount: 326124,
    posAmount: 46686,
  },
  {
    sl: 58,
    nbfcId: "MFL812306873",
    appId: "APP4642197907",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 42,
    nbfcDisbursedAmount: 477358,
    posAmount: 167455,
  },
  {
    sl: 59,
    nbfcId: "MFL532074125",
    appId: "APP8289454630",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 42,
    nbfcDisbursedAmount: 390671,
    posAmount: 76735,
  },
  {
    sl: 60,
    nbfcId: "MFL507104143",
    appId: "APP4877520294",
    status: "Approved",
    name: "Quantum Loans",
    tenure: 72,
    nbfcDisbursedAmount: 422707,
    posAmount: 308375,
  },
  {
    sl: 61,
    nbfcId: "MFL995205588",
    appId: "APP5296710795",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 60,
    nbfcDisbursedAmount: 250425,
    posAmount: 65098,
  },
  {
    sl: 62,
    nbfcId: "MFL802984810",
    appId: "APP6679017210",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 66,
    nbfcDisbursedAmount: 331623,
    posAmount: 241819,
  },
  {
    sl: 63,
    nbfcId: "MFL952266893",
    appId: "APP5659161352",
    status: "Approved",
    name: "Beta Credit",
    tenure: 54,
    nbfcDisbursedAmount: 370245,
    posAmount: 358050,
  },
  {
    sl: 64,
    nbfcId: "MFL822408848",
    appId: "APP2333241445",
    status: "Rejected",
    name: "Titanium",
    tenure: 30,
    nbfcDisbursedAmount: 204401,
    posAmount: 48627,
  },
  {
    sl: 65,
    nbfcId: "MFL610173760",
    appId: "APP4300636585",
    status: "Approved",
    name: "Titanium",
    tenure: 30,
    nbfcDisbursedAmount: 338769,
    posAmount: 227286,
  },
  {
    sl: 66,
    nbfcId: "MFL529123992",
    appId: "APP2047905204",
    status: "Approved",
    name: "Quantum Loans",
    tenure: 54,
    nbfcDisbursedAmount: 443963,
    posAmount: 370512,
  },
  {
    sl: 67,
    nbfcId: "MFL334978881",
    appId: "APP7519578899",
    status: "Approved",
    name: "Titanium",
    tenure: 48,
    nbfcDisbursedAmount: 126328,
    posAmount: 83060,
  },
  {
    sl: 68,
    nbfcId: "MFL243171768",
    appId: "APP8737025391",
    status: "Approved",
    name: "Titanium",
    tenure: 54,
    nbfcDisbursedAmount: 450002,
    posAmount: 288466,
  },
  {
    sl: 69,
    nbfcId: "MFL975106572",
    appId: "APP7462972995",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 66,
    nbfcDisbursedAmount: 387242,
    posAmount: 243787,
  },
  {
    sl: 70,
    nbfcId: "MFL378304807",
    appId: "APP4228856718",
    status: "Approved",
    name: "Quantum Loans",
    tenure: 54,
    nbfcDisbursedAmount: 434318,
    posAmount: 155391,
  },
  {
    sl: 71,
    nbfcId: "MFL572309605",
    appId: "APP9922723063",
    status: "Rejected",
    name: "Ultrasonic United",
    tenure: 36,
    nbfcDisbursedAmount: 249803,
    posAmount: 71471,
  },
  {
    sl: 72,
    nbfcId: "MFL679984033",
    appId: "APP1346078411",
    status: "Rejected",
    name: "Alpha Finance",
    tenure: 42,
    nbfcDisbursedAmount: 179078,
    posAmount: 70623,
  },
  {
    sl: 73,
    nbfcId: "MFL168965204",
    appId: "APP7076811348",
    status: "Rejected",
    name: "Ultrasonic United",
    tenure: 30,
    nbfcDisbursedAmount: 273477,
    posAmount: 254278,
  },
  {
    sl: 74,
    nbfcId: "MFL994310083",
    appId: "APP7099469983",
    status: "Rejected",
    name: "Titanium",
    tenure: 30,
    nbfcDisbursedAmount: 406225,
    posAmount: 374654,
  },
  {
    sl: 75,
    nbfcId: "MFL612153089",
    appId: "APP6805759868",
    status: "Approved",
    name: "Beta Credit",
    tenure: 48,
    nbfcDisbursedAmount: 495037,
    posAmount: 214465,
  },
  {
    sl: 76,
    nbfcId: "MFL958851904",
    appId: "APP6242173772",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 60,
    nbfcDisbursedAmount: 215040,
    posAmount: 81548,
  },
  {
    sl: 77,
    nbfcId: "MFL517532243",
    appId: "APP1116402431",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 12,
    nbfcDisbursedAmount: 436985,
    posAmount: 234716,
  },
  {
    sl: 78,
    nbfcId: "MFL153992714",
    appId: "APP6412330148",
    status: "Approved",
    name: "Quantum Loans",
    tenure: 24,
    nbfcDisbursedAmount: 271627,
    posAmount: 65485,
  },
  {
    sl: 79,
    nbfcId: "MFL917364173",
    appId: "APP9072992279",
    status: "Rejected",
    name: "Alpha Finance",
    tenure: 42,
    nbfcDisbursedAmount: 245886,
    posAmount: 207134,
  },
  {
    sl: 80,
    nbfcId: "MFL604988121",
    appId: "APP9673185158",
    status: "Rejected",
    name: "Alpha Finance",
    tenure: 18,
    nbfcDisbursedAmount: 382810,
    posAmount: 37307,
  },
  {
    sl: 81,
    nbfcId: "MFL173678414",
    appId: "APP3799264931",
    status: "Rejected",
    name: "Ultrasonic United",
    tenure: 72,
    nbfcDisbursedAmount: 495435,
    posAmount: 26268,
  },
  {
    sl: 82,
    nbfcId: "MFL767154083",
    appId: "APP1654477195",
    status: "Approved",
    name: "Ultrasonic United",
    tenure: 12,
    nbfcDisbursedAmount: 166176,
    posAmount: 134141,
  },
  {
    sl: 83,
    nbfcId: "MFL599326438",
    appId: "APP8299146480",
    status: "Approved",
    name: "Beta Credit",
    tenure: 30,
    nbfcDisbursedAmount: 293407,
    posAmount: 97969,
  },
  {
    sl: 84,
    nbfcId: "MFL216070149",
    appId: "APP3485432021",
    status: "Approved",
    name: "Ultrasonic United",
    tenure: 36,
    nbfcDisbursedAmount: 263555,
    posAmount: 160941,
  },
  {
    sl: 85,
    nbfcId: "MFL181600593",
    appId: "APP2043030161",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 30,
    nbfcDisbursedAmount: 465529,
    posAmount: 415002,
  },
  {
    sl: 86,
    nbfcId: "MFL954942461",
    appId: "APP4361393222",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 18,
    nbfcDisbursedAmount: 282034,
    posAmount: 234593,
  },
  {
    sl: 87,
    nbfcId: "MFL795294275",
    appId: "APP2465576748",
    status: "Rejected",
    name: "Titanium",
    tenure: 60,
    nbfcDisbursedAmount: 320231,
    posAmount: 267006,
  },
  {
    sl: 88,
    nbfcId: "MFL782454310",
    appId: "APP5952059278",
    status: "Approved",
    name: "Quantum Loans",
    tenure: 42,
    nbfcDisbursedAmount: 192346,
    posAmount: 146772,
  },
  {
    sl: 89,
    nbfcId: "MFL931764920",
    appId: "APP7371573279",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 60,
    nbfcDisbursedAmount: 328366,
    posAmount: 320627,
  },
  {
    sl: 90,
    nbfcId: "MFL991990632",
    appId: "APP5014170428",
    status: "Rejected",
    name: "Alpha Finance",
    tenure: 30,
    nbfcDisbursedAmount: 246238,
    posAmount: 241114,
  },
  {
    sl: 91,
    nbfcId: "MFL711871397",
    appId: "APP6922713963",
    status: "Rejected",
    name: "Ultrasonic United",
    tenure: 54,
    nbfcDisbursedAmount: 115047,
    posAmount: 74789,
  },
  {
    sl: 92,
    nbfcId: "MFL327761953",
    appId: "APP6404582459",
    status: "Rejected",
    name: "Ultrasonic United",
    tenure: 54,
    nbfcDisbursedAmount: 246621,
    posAmount: 240770,
  },
  {
    sl: 93,
    nbfcId: "MFL654724287",
    appId: "APP5071897791",
    status: "Rejected",
    name: "Beta Credit",
    tenure: 12,
    nbfcDisbursedAmount: 144885,
    posAmount: 73270,
  },
  {
    sl: 94,
    nbfcId: "MFL914073098",
    appId: "APP8352307139",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 60,
    nbfcDisbursedAmount: 334972,
    posAmount: 19040,
  },
  {
    sl: 95,
    nbfcId: "MFL534222401",
    appId: "APP3971203213",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 30,
    nbfcDisbursedAmount: 260540,
    posAmount: 184053,
  },
  {
    sl: 96,
    nbfcId: "MFL670073085",
    appId: "APP6771394050",
    status: "Rejected",
    name: "Quantum Loans",
    tenure: 60,
    nbfcDisbursedAmount: 491084,
    posAmount: 298562,
  },
  {
    sl: 97,
    nbfcId: "MFL390894296",
    appId: "APP6611903015",
    status: "Rejected",
    name: "Alpha Finance",
    tenure: 54,
    nbfcDisbursedAmount: 220868,
    posAmount: 41629,
  },
  {
    sl: 98,
    nbfcId: "MFL897662466",
    appId: "APP1795212538",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 18,
    nbfcDisbursedAmount: 213447,
    posAmount: 203620,
  },
  {
    sl: 99,
    nbfcId: "MFL916267011",
    appId: "APP6128695961",
    status: "Rejected",
    name: "Alpha Finance",
    tenure: 66,
    nbfcDisbursedAmount: 219266,
    posAmount: 104602,
  },
  {
    sl: 100,
    nbfcId: "MFL860229059",
    appId: "APP3294092753",
    status: "Approved",
    name: "Alpha Finance",
    tenure: 12,
    nbfcDisbursedAmount: 243818,
    posAmount: 21931,
  },
];